credential_path: "~/.local/etc/fanc_credentials.yaml"

braincircuits:
  base_url: "https://api.braincircuits.io"
  dump_interval: 3600    # expect a new dump every dump_interval seconds

cave:
  dataset: fanc_production_mar2021
  ref_version: 506
  tables:
    soma: neuron_somas_dec2022
    leg_mn: all_leg_motor_neuron_table_v0
    haltere_mn: haltere_motor_neuron_table_v0
    wing_mn: wing_motor_neuron_table_v0
    neck_mn: neck_motor_neuron_table_v0
    nerve_bundle: nerve_bundle_fibers_v0

local:
  data: "~/Data/fanc/fancpq"

criteria:
  orphaned_soma:
    max_synapse_count: 10